const { paths } = require('./paths')
const { HtmlWebpackPlugin, MiniCssExtractPlugin, CopyPlugin, CleanWebpackPlugin } = require('./deps')

const title = 'VC Webpack Boilerplate'
const plugins = [
    /**
     * Generates dynamic Html file from a template.
     */
    new HtmlWebpackPlugin({
        title: title,
        favicon: `${paths.static}/favicon-32x32.png`,
        template: `${paths.app}/index.html`,
        filename: 'index.html'
    }),

    /**
     * Extract CSS into separate files.
     */
    new MiniCssExtractPlugin({
        filename: 'css/[name].css'
    }),

    /**
     * Copy files from the specified directory to output_dir.
     * Useful for copying static files not generated by webpack.
     */
    new CopyPlugin({
        patterns: [
            { from: paths.static }
        ]
    }),

    /**
     * Remove/clean build folders.
     */
    new CleanWebpackPlugin(),
]

module.exports = { plugins }